DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
    ID NUMBER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(250) NOT NULL,
    DESCRIPTION VARCHAR(250),
    BRAND VARCHAR(250),
    COLOR VARCHAR(250),
    QUANTITY NUMBER DEFAULT 0,
    PRICE DOUBLE DEFAULT 0.0,
    UPDATED_DATE NUMBER(20)
);

ALTER TABLE PRODUCT ADD CONSTRAINT UK_QUANTITY_NOT_NEGATIVE CHECK (QUANTITY >= 0);

DROP TABLE IF EXISTS CUSTOMER_ACTIVITY;
CREATE TABLE CUSTOMER_ACTIVITY (
    ID NUMBER AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(250) NOT NULL,
    CUSTOMER_ACTION VARCHAR(250) NOT NULL,
    PARAMS VARCHAR(1000) NOT NULL,
    ACTION_TIME NUMBER(20)
);

DROP TABLE IF EXISTS ORDER_BASKET;
CREATE TABLE ORDER_BASKET (
    ID NUMBER AUTO_INCREMENT PRIMARY KEY,
    ORDER_DETAIL TEXT NOT NULL,
    ORDER_STATUS VARCHAR(250) NOT NULL,
    TOTAL_PRICE DOUBLE DEFAULT 0.0,
    CREATED_DATE NUMBER(20),
    UPDATED_DATE NUMBER(20)
);
