DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
    ID NUMBER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(250) NOT NULL,
    DESCRIPTION VARCHAR(250),
    BRAND VARCHAR(250),
    COLOR VARCHAR(250),
    QUANTITY NUMBER DEFAULT 0,
    PRICE DOUBLE DEFAULT 0.0,
    UPDATED_TIME NUMBER(20)
);

ALTER TABLE PRODUCT ADD CONSTRAINT UK_QUANTITY_NOT_NEGATIVE CHECK (QUANTITY > 0);